MvcCoffeeShop/Controllers/NguoiDungController.cs
using MvcCoffeeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;

namespace MvcCoffeeShop.Controllers
{
    public class NguoiDungController : Controller
    {
        QLQUANCAPHEEntities2 databases = new QLQUANCAPHEEntities2();

        // GET: NguoiDung
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(kh.TenKH))
                    ModelState.AddModelError(string.Empty, "Họ tên không được để trống");
                if (string.IsNullOrEmpty(kh.TenDN))
                    ModelState.AddModelError(string.Empty, "Tên đăng nhập không được để trống");
                if (string.IsNullOrEmpty(kh.MatKhau))
                    ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
                if (kh.MatKhau.Length < 6)
                    ModelState.AddModelError(string.Empty, "Mật khẩu phải có ít nhất 6 ký tự");
                if (string.IsNullOrEmpty(kh.Email))
                    ModelState.AddModelError(string.Empty, "Email không được để trống");

                if (!Regex.IsMatch(kh.Email, @"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$"))
                {
                    ModelState.AddModelError(string.Empty, "Địa chỉ Email không hợp lệ");
                }

                if (string.IsNullOrEmpty(kh.SoDienThoai) || kh.SoDienThoai.Length > 10 || !Regex.IsMatch(kh.SoDienThoai, @"^\d{10}$"))
                {
                    ModelState.AddModelError(string.Empty, "Số điện thoại không hợp lệ");
                }

                if (kh.NgaySinh > DateTime.Now)
                {
                    ModelState.AddModelError(string.Empty, "Ngày sinh không được lớn hơn ngày hiện tại");
                }


                //Kiểm tra tên đăng nhập đã tồn tại hay chưa
                var khachhang = databases.KhachHangs.FirstOrDefault(k => k.TenDN == kh.TenDN);
                if (khachhang != null)
                    ModelState.AddModelError(string.Empty, "Tên đăng nhập đã tồn tại");

                if (ModelState.IsValid)
                {
                    databases.KhachHangs.Add(kh);
                    databases.SaveChanges();
                }
                else
                {
                    return View();
                }
            }
            return RedirectToAction("DangNhap");
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(kh.TenDN))
                    ModelState.AddModelError(string.Empty, "Tên đăng nhập không được để trống");
                if (string.IsNullOrEmpty(kh.MatKhau))
                    ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
                if (kh.MatKhau.Length < 6)
                    ModelState.AddModelError(string.Empty, "Mật khẩu phải có ít nhất 6 ký tự");
            }
            if (ModelState.IsValid)
            {
                var khach = databases.KhachHangs.FirstOrDefault(k => k.TenDN == kh.TenDN && k.MatKhau == kh.MatKhau);
                if (khach != null)
                {
                    ViewBag.ThongBao = "Đăng nhập thành công";
                    // Lưu vào session
                    Session["TaiKhoan"] = khach;
                }
                else
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

MvcCoffeeShop/Views/NguoiDung/DangKy.cshtml
    
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_LayoutNone.cshtml";
}

<h2 style="text-align: center">ĐĂNG KÝ THÀNH VIÊN</h2>
<br />
<div class="row">
    <div class="offset-md-1 col-md-10">
        @using (Html.BeginForm("DangKy", "NguoiDung"))
        {
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="name">Họ và Tên:</label>
                @Html.TextBox("TenKH", null, new
                {
                    @class = "form-control",
                    @id =
               "name",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="dangnhap">Tên đăng nhập:</label>
                @Html.TextBox("TenDN", null, new
                {
                    @class = "form-control",
                    @id =
               "dangnhap",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="matkhau">Mật khẩu:</label>
                @Html.Password("MatKhau", null, new
                {
                    @class = "form-control",
                    @id =
               "matkhau",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                @Html.TextBox("Email", null, new
                {
                    @class = "form-control",
                    @id =
               "email",
                    type = "email",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="diachi">Địa chỉ:</label>
                @Html.TextBox("DiaChi", null, new
                {
                    @class = "form-control",
                    @id =
               "diachi"
                })
            </div>
            <div class="form-group">
                <label for="dienthoai">Điện thoại:</label>
                @Html.TextBox("SoDienThoai", null, new
                {
                    @class = "form-control",
                    @id =
               "dienthoai",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="ngaysinh">Ngày sinh:</label>
                @Html.TextBox("NgaySinh", null, new
                {
                    @class = "form-control",
                    @id =
               "ngaysinh",
                    type = "date",
                    placeholder = "mm/dd/yyyy"
                })
            </div>
            <button type="submit" class="btn btn-primary">ĐĂNG KÝ</button>
        }
    </div>
</div>

MvcCoffeeShop/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_LayoutNone.cshtml";
}

<h2 style="text-align: center">ĐĂNG NHẬP</h2>
<br />
<div class="row">
    <div class="offset-md-1 col-md-10">
        <h2 style="color: red;">@ViewBag.ThongBao</h2>
        @using (Html.BeginForm("DangNhap", "NguoiDung"))
        {
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="dangnhap">Tên đăng nhập:</label>
                @Html.TextBox("TenDN", null, new
                {
                    @class = "form-control",
                    @id =
               "dangnhap",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="matkhau">Mật khẩu:</label>
                @Html.Password("Matkhau", null, new
                {
                    @class = "form-control",
                    @id =
               "matkhau",
                    required = "required"
                })
            </div>
            <button type="submit" class="btn btn-primary">ĐĂNG NHẬP</button>
        }
    </div>
</div>