MvcCoffeeShop/Controllers/CoffeeShopController.cs
using MvcCoffeeShop.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;

namespace MvcCoffeeShop.Controllers
{
    public class CoffeeShopController : Controller
    {
        // Use DbContext to manage database
        QLQUANCAPHEEntities2 database = new QLQUANCAPHEEntities2();
        private List<SanPham> LaySanPham(int soluong)
        {
            //Sắp xếp sản phẩm theo tên và lọc theo mã phân loại, lấy đúng số lượng sản phẩm cần
            return database.SanPhams
                .OrderBy(sanpham => sanpham.TenSanPham)
                .Take(soluong)
                .ToList();
        }


        // GET: CoffeeShop
        public ActionResult Index(string maPhanLoai)
        {
            var dsSanPham = LaySanPham(5);

            return View(dsSanPham);
        }

        public ActionResult LayThucUong()
        {
            var dsThucUong = database.PhanLoais.ToList();
            return PartialView(dsThucUong);
        }

        public ActionResult SPTheoPhanLoai(string id, int? page)
        {
            ViewBag.CategoryId = id;

            int pageSize = 5; // Số sản phẩm trên mỗi trang
            int pageNum = (page ?? 1); // Số trang hiện tại

            // Lấy các sản phẩm theo mã phân loại
            var dsSanPhamTheoPhanLoai = database.SanPhams
                .Where(sanpham => sanpham.MaPhanLoai == id)
                .OrderBy(sanpham => sanpham.TenSanPham)
                .ToPagedList(pageNum, pageSize);

            // Trả về View để render các sản phẩm
            return View(dsSanPhamTheoPhanLoai);
        }

        public ActionResult Details(string id)
        {
            //Lây sản phẩm có mã tương ứng
            var sanpham = database.SanPhams.FirstOrDefault(sp => sp.MaSanPham == id);
            return View(sanpham);
        }
        public ActionResult Products(string id, int? page)
        {

            int pageSize = 5; //Tạo biến cho biết số sản phẩm mỗi trang
            int pageNum = (page ?? 1); //Tạo biến số trang

            //Giả sử cần lấy 24 sản phẩm mới cập nhật
            var dsSanPham = LaySanPham(24);
            return View(dsSanPham.ToPagedList(pageNum, pageSize));


        }
        //public ActionResult Products(int? page)
        //{
        //    int pageSize = 5; //Tạo biến cho biết số sản phẩm mỗi trang
        //    int pageNum = (page ?? 1); //Tạo biến số trang

        //    //Giả sử cần lấy 15 quyển sách mới cập nhật
        //    var dsSanPham = LaySanPham(24);
        //    return View(dsSanPham.ToPagedList(pageNum, pageSize));
        //}
    }
}

MvcCoffeeShop/Views/CoffeeShop/Details.cshtml
@using MvcCoffeeShop.Models
@model SanPham
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutSingle.cshtml";
}

<div id="fh5co-product">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 animate-box">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <img src="~/Content/Images2/@Model.HinhAnh" alt="user">
                        <h2>@Model.TenSanPham</h2>
                        <p>
                            <a href="@Url.Action("ThemSanPhamVaoGio", "GioHang", new { MaSP = Model.MaSanPham.Trim() })"
                               class="btn btn-primary btn-outline btn-lg">Add to Cart</a>
                            <a href="#" class="btn btn-primary btn-outline btn-lg">Compare</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="fh5co-tabs animate-box">
            <ul class="fh5co-tab-nav">
                <li class="active"><a href="#" data-tab="1"><span class="icon visible-xs"><i class="icon-file"></i></span><span class="hidden-xs">Product Details</span></a></li>
                <li><a href="#" data-tab="2"><span class="icon visible-xs"><i class="icon-bar-graph"></i></span><span class="hidden-xs">Hướng dẫn sử dụng</span></a></li>
                <li><a href="#" data-tab="3"><span class="icon visible-xs"><i class="icon-star"></i></span><span class="hidden-xs">Feedback &amp; Ratings</span></a></li>
            </ul>

            <!-- Tabs -->
            <div class="fh5co-tab-content-wrap">

                <div class="fh5co-tab-content tab-content active" data-tab-content="1">
                    <div class="col-md-10 col-md-offset-1">
                        <span class="price">Giá: @Model.GiaBan đ</span>
                        <h2>@Model.TenSanPham</h2>
                        <p>@Model.MoTa</p>

                        <div class="row">
                            <div class="col-md-6">
                                <h2 class="uppercase">Keep it simple</h2>
                                <p>Ullam dolorum iure dolore dicta fuga ipsa velit veritatis</p>
                            </div>
                            <div class="col-md-6">
                                <h2 class="uppercase">Less is more</h2>
                                <p>Ullam dolorum iure dolore dicta fuga ipsa velit veritatis</p>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="fh5co-tab-content tab-content" data-tab-content="2">
                    <div class="col-md-10 col-md-offset-1">
                        <h3>Hướng dẫn sử dụng sản phẩm</h3>
                        <ul>
                            <li>Paragraph placeat quis fugiat provident veritatis quia iure a debitis adipisci dignissimos consectetur magni quas eius</li>
                            <li>adipisci dignissimos consectetur magni quas eius nobis reprehenderit soluta eligendi</li>
                            <li>Veritatis tenetur odio delectus quibusdam officiis est.</li>
                            <li>Magni quas eius nobis reprehenderit soluta eligendi quo reiciendis fugit? Veritatis tenetur odio delectus quibusdam officiis est.</li>
                        </ul>
                    </div>
                </div>

                <div class="fh5co-tab-content tab-content" data-tab-content="3">
                    <div class="col-md-10 col-md-offset-1">
                        <h3>Happy Buyers</h3>
                        <div class="feed">
                            <div>
                                <blockquote>
                                    <p>Paragraph placeat quis fugiat provident veritatis quia iure a debitis adipisci dignissimos consectetur magni quas eius nobis reprehenderit soluta eligendi quo reiciendis fugit? Veritatis tenetur odio delectus quibusdam officiis est.</p>
                                </blockquote>
                                <h3>&mdash; Louie Knight</h3>
                                <span class="rate">
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                </span>
                            </div>
                            <div>
                                <blockquote>
                                    <p>Paragraph placeat quis fugiat provident veritatis quia iure a debitis adipisci dignissimos consectetur magni quas eius nobis reprehenderit soluta eligendi quo reiciendis fugit? Veritatis tenetur odio delectus quibusdam officiis est.</p>
                                </blockquote>
                                <h3>&mdash; Joefrey Gwapo</h3>
                                <span class="rate">
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                    <i class="icon-star2"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<!--<h2>THÔNG TIN CHI TIẾT SẢN PHẨM</h2>
<br />
<div class="row">
    <div class="offset-md-1 col-md-4">
        <img style="width: 100%;" src="~/Content/Images2/@Model.HinhAnh" alt="" />
    </div>
    <div class="col-md-6 details">
        <h3>Tên sản phẩm: @Model.TenSanPham</h3>
        <p style="text-align: justify">
            <span style="font-weight: bold">Mô tả:</span> @Model.MoTa
        </p>
        <p class="price">
            GIá bán: <span style="color:red; font-size: 32px;"> @Model.GiaBan VNĐ</span>
        </p>
    </div>
</div>-->

MvcCoffeeShop/Views/CoffeeShop/Index.cshtml
@using MvcCoffeeShop.Models
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="fh5co-product">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <span>Cool Stuff</span>
                <h2>Sản Phẩm</h2>
                <p>
                    Từ hương thơm phức tạp đến vị đắng đặc trưng, cà phê đem lại trải nghiệm tinh tế cho người thưởng thức,
                    là nguồn năng lượng và nguồn cảm hứng cho những người yêu thích thưởng thức đồ uống đậm đà.
                </p>
            </div>
        </div>

        <div class="row">
            @foreach (var sanpham in Model)
            {
                <div class="col-md-4 text-center animate-box">
                    <div class="product">
                        <div class="product-grid" style="background-image: url(/Content/Images2/@sanpham.HinhAnh)">

                            <div class="inner">
                                <p>
                                    <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                                       class="icon"><i class="icon-shopping-cart"></i></a>
                                    <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                                       class="icon"><i class="icon-eye"></i></a>
                                </p>
                            </div>
                        </div>
                        <div class="desc">
                            <h3>
                                <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})">
                                    @sanpham.TenSanPham
                                </a>
                            </h3>
                            <span class="price">@sanpham.GiaBan</span>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

MvcCoffeeShop/Views/CoffeeShop/LayThucUong.cshtml
@using MvcCoffeeShop.Models
@model IEnumerable<PhanLoai>
<div class="title">Menu</div>
<ul class="list-group">
    @foreach (var phanloai in Model)
    {
        <a href="@Url.Action("SPTheoThucUong", "CoffeeShop", new { id=phanloai.MaPhanLoai })"
           class="list-group-item list-group-item-action">
            @phanloai.TenPhanLoai
        </a>
    }
</ul>

MvcCoffeeShop/Views/CoffeeShop/Products.cshtml
@using MvcCoffeeShop.Models
@using PagedList.Mvc
@model PagedList.PagedList<SanPham>
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_LayoutProduct.cshtml";
}

<div class="row">
    @foreach (var sanpham in Model)
    {
        <div class="col-md-4 text-center animate-box">
            <div class="product">
                <div class="product-grid" style="background-image: url(/Content/Images2/@sanpham.HinhAnh)">

                    <div class="inner">
                        <p>
                            <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                               class="icon"><i class="icon-shopping-cart"></i></a>
                            <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                               class="icon"><i class="icon-eye"></i></a>
                        </p>
                    </div>
                </div>
                <div class="desc">
                    <h3>
                        <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})">
                            @sanpham.TenSanPham
                        </a>
                    </h3>
                    <span class="price">@sanpham.GiaBan</span>
                </div>
            </div>
        </div>
    }

</div>

<!-- Thêm mã phân trang -->
<br />
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Products", new { page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<!-- Kết thúc -->

MvcCoffeeShop/Views/CoffeeShop/SPTheoPhanLoai.cshtml
@using MvcCoffeeShop.Models
@using PagedList.Mvc
@model PagedList.PagedList<SanPham>

@{
    ViewBag.Title = "SPTheoPhanLoai";
    Layout = "~/Views/Shared/_LayoutProduct.cshtml";
}

<div class="row">
    @foreach (var sanpham in Model)
    {
        <div class="col-md-4 text-center animate-box">
            <div class="product">
                <div class="product-grid" style="background-image: url(/Content/Images2/@sanpham.HinhAnh)">

                    <div class="inner">
                        <p>
                            <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                               class="icon"><i class="icon-shopping-cart"></i></a>
                            <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})"
                               class="icon"><i class="icon-eye"></i></a>
                        </p>
                    </div>
                </div>
                <div class="desc">
                    <h3>
                        <a href="@Url.Action("Details", "CoffeeShop", new { id = sanpham.MaSanPham.Trim()})">
                            @sanpham.TenSanPham
                        </a>
                    </h3>
                    <span class="price">@sanpham.GiaBan</span>
                </div>
            </div>
        </div>
    }
</div>

<!-- Thêm mã phân trang -->
<br />
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
<div class="MenuTrang">
    @*@Html.PagedListPager(Model, page => Url.Action("SPTheoPhanLoai", new { page }))*@
    @Html.PagedListPager(Model, page => Url.Action("SPTheoPhanLoai", new { id = ViewBag.CategoryId, page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<!-- Kết thúc -->